### ISSUE TITLE
Unexpected behavior with `<rational>` number translated from its `<decimal>` notation.

### ISSUE THREAD

**Issue by Mallku2** [cvc5/ethos#88]
For an Eunoia proof certificate that begins like:

```
(declare-type Real ())
(declare-consts <rational> Real)

(declare-const a Real)
(declare-const = (-> (! Type :var A :implicit) A A Bool))

(assume p (= a 2.1))
```

Ethos complains with the following error message:

```
Error: test.eo:7.19: Type checking failed:
Expression: ((= a) 21/10)
Message: Unexpected argument type 0 of (= a)
  LHS Real, from Real
  RHS ?
  Context []
```

Where the `<decimal>` number was converted to `<rational>` notation during lexing (?) (I am invoking Ethos with default behavior) and, yet, the type checker cannot build a proof showing that 21/10 inhabits Real: `TYPE 21/10 : ?`.
However, if I change 2.1 to 21/10 in the previous proof certificate, Ethos accepts it and now `TYPE 21/10 : Real`. What am I missing here?

I am using an Ethos binary compiled from the main branch, up to date.

**Comment by ajreynol** [comment]
In ethos 0.1.1 prerelease (main), decimals are no longer normalized to rationals when parsing *.eo files (although they still are normalized to rationals by default when parsing proofs and *.smt2). 

See the first item here: https://github.com/cvc5/ethos/blob/main/NEWS.md

This change was made so that the definition of the Eunoia language is more consistent. In particular, parsing *.eo is no longer impacted by user options.  Generally speaking, you should avoid using decimals in proof signature files unless you want to consider decimals and rationals as 2 different things.

Note that if your proof has a file extension different from *.eo, we consider it to be a "proof" file now, see the explanation here: https://github.com/cvc5/ethos/blob/main/user_manual.md#full-syntax-for-eunoia-commands

**Comment by Mallku2** [comment]
Perfect, many thanks!
